version: "3"

volumes:
  node_modules:
    driver: "local"

services:
  amsc:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: amsc
    container_name: amsc
    tty: true
    stdin_open: true
    init: true
    environment:
      NODE_PATH: /usr/local/lib/node_modules
      TZ: Asia/Tokyo
    restart: always
    working_dir: /app/
    volumes:
      - ./app/:/app/
      - node_modules:/app/node_modules
    command: npm run start
